server:
  port: 8084


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-wz928az8hh05yusb0po.mysql.rds.aliyuncs.com:3306/user_open
    username: useropen123
    password: iksdfjdksl@#djioiAAbb3223
  jdbc:
    template:
      fetch-size: 10

mybatis:
  #加载 mapper.xml 文件到容器中
  mapper-locations: classpath:mapper/*.xml
  #别名，简化 mapper.xml 中请求响应参数类型
  type-aliases-package: com.user.opentest.model
  configuration:
    #开启驼峰映射
    map-underscore-to-camel-case: false
    #sql日志的打印
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl

